version: "3"
services:
  server:
    container_name: weather-server
    restart: always
    build: ./server
    ports:
      - "3030:3030"
    external_links:
      - mongo
  node:
    container_name: weather-node
    restart: always
    build: ./node
    ports:
      - "3000:3000"
    external_links:
      - server
  mongo:
    container_name: weather-mongo
    image: mongo
    ports:
      - "27017:27017"
